### ISSUE TITLE
Add Weight to Penalty graph?

### ISSUE THREAD

**Issue by vorburger** [31z4/saturn-moonlet#4]
Might it be useful to add the Weight to the Penalty graph as well?

This may make seeing correlation of Weight drops by penalty more directly obvious...

... iff that's how Saturn even works? (Which I suspect, but am not really sure of myself; see also #3.)

**Comment by 31z4** [comment]
It seems to me that there's a clear correlation between Weight and Bias. But it's not that obvious for the Penalty.

<img width="1708" alt="image" src="https://github.com/31z4/saturn-moonlet/assets/3657959/2ff3f47d-c66e-4b80-8e63-b11c9febd995">

There's 7 kinds of penalties at the moment and their sum can go above `1`. Can you maybe suggest an exact query to plot?
